USE [product_api_db];
GO


CREATE TABLE [USER]
(
    USER_NAME        NVARCHAR(10)  NOT NULL,
    USER_FULL_NAME   NVARCHAR(100) NOT NULL,
    USER_PASSWORD    NVARCHAR(512) NOT NULL,
    USER_CREATE_DATE DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_LAST_LOGIN  DATETIME,
    USER_ROLE        NVARCHAR(5)            DEFAULT 'USER',
    USER_STATUS      BIT                    DEFAULT 1,
    CONSTRAINT PK_USER_ID PRIMARY KEY (USER_NAME)
);
GO


CREATE TABLE [CATEGORY]
(
    CAT_ID          BIGINT IDENTITY (1,1) NOT NULL,
    CAT_NAME        NVARCHAR(50)          NOT NULL,
    CAT_CREATE_DATE DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CAT_LAST_UPDATE DATETIME,
    CAT_STATUS      BIT                            DEFAULT 1,
    CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (CAT_ID)
);
GO

CREATE TABLE [PRODUCT]
(
    PROD_ID          BIGINT IDENTITY (1,1) NOT NULL,
    PROD_NAME        NVARCHAR(50)          NOT NULL,
    PROD_COST        NUMERIC(10, 2),
    PROD_PRICE       NUMERIC(10, 2),
    PROD_TAGS        NVARCHAR(100),
    PROD_CREATE_DATE DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROD_LAST_UPDATE DATETIME,
    PROD_STATUS      BIT                            DEFAULT 1,
    CAT_ID           BIGINT                NULL
        CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (PROD_ID),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CAT_ID)
        REFERENCES [CATEGORY] (CAT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
GO


